# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 谁的青春不迷茫
email: info@newteo.com
description: > # this means to ignore newlines until "baseurl:"
  你在南方的艳阳里大学纷飞
  我在北方的寒夜里四季如春
baseurl: "/blog3" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: newteo
github_username:  shenmiaoling

# Build settings
markdown: kramdown
